#!/bin/bash

if [ $# -lt 1 ]; then
    echo "USAGE: $0 <repository> [--purge]"
    exit 1
fi

SOURCE_REPO="$1"
REMOVE_OLD=false

if [ $# -eq 2 ] && [ "$2" = "--purge" ]; then
    REMOVE_OLD=true
fi

# List all tags of the source repository
TAGS=$(docker image ls | grep $SOURCE_REPO | awk '{print $1":"$2}' )

for TAG in $TAGS; do
    echo "Pushing $TAG"
    # Push the newly tagged image
    docker push $TAG

    # Optionally, remove the old image
    if [ "$REMOVE_OLD" = true ]; then
        docker image rm $TAG
    fi
done