#!/bin/bash

if [ $# -lt 2 ]; then
    echo "USAGE: $0 <repository> [--purge]"
    exit 1
fi

SOURCE_REPO="$1"
REMOVE_OLD=false

if [ $# -eq 2 ] && [ "$2" = "--purge" ]; then
    REMOVE_OLD=true
fi

# List all tags of the source repository
TAGS=$(docker image ls --format "{{.Tag}}" "$SOURCE_REPO")

for TAG in $TAGS; do

    # Push the newly tagged image
    docker push "$SOURCE_REPO:$TAG"

    # Optionally, remove the old image
    if [ "$REMOVE_OLD" = true ]; then
        docker image rm "$SOURCE_REPO:$TAG"
    fi
done